---

gateways:
  - gateway_configuration:
      exclude_env_in_app_name: true
      private_ip_address: 10.180.13.10
    ssl_certificates:
      - certificate_name: wildcard-ithc-api-hmcts-net
    app_configuration:
      - product: sps
        component: apim-gateway-public
        ssl_enabled: true
        backend_protocol: Https
        use_public_ip: true
        host_name_prefix: sps-api-mgmt
        health_path_override: "/status-0123456789abcdef"
        ssl_certificate_name: wildcard-ithc-api-hmcts-net
        host_name_suffix: ithc.api.hmcts.net
        ssl_host_name_suffix: ithc.api.hmcts.net
      - product: sps
        component: apim-portal-public
        ssl_enabled: true
        backend_protocol: Https
        use_public_ip: true
        host_name_prefix: amp-portal
        health_path_override: "/signin"
        ssl_certificate_name: wildcard-ithc-api-hmcts-net
        host_name_suffix: ithc.api.hmcts.net
        ssl_host_name_suffix: ithc.api.hmcts.net
      - product: sps
        component: apim-management-public
        ssl_enabled: true
        backend_protocol: Https
        use_public_ip: true
        host_name_prefix: management
        health_path_override: "/ServiceStatus"
        ssl_certificate_name: wildcard-ithc-api-hmcts-net
        host_name_suffix: ithc.api.hmcts.net
        ssl_host_name_suffix: ithc.api.hmcts.net
      - product: sps
        component: apim-gateway-private
        ssl_enabled: true
        backend_protocol: Https
        use_private_ip: true
        host_name_prefix: sps-api-mgmt
        health_path_override: "/status-0123456789abcdef"
        ssl_certificate_name: wildcard-ithc-api-hmcts-net
        host_name_suffix: ithc.api.hmcts.net
        ssl_host_name_suffix: ithc.api.hmcts.net
      - product: sps
        component: apim-portal-private
        ssl_enabled: true
        backend_protocol: Https
        use_private_ip: true
        host_name_prefix: amp-portal
        health_path_override: "/signin"
        ssl_certificate_name: wildcard-ithc-api-hmcts-net
        host_name_suffix: ithc.api.hmcts.net
        ssl_host_name_suffix: ithc.api.hmcts.net
      - product: sps
        component: apim-management-private
        ssl_enabled: true
        backend_protocol: Https
        use_private_ip: true
        host_name_prefix: management
        health_path_override: "/ServiceStatus"
        ssl_certificate_name: wildcard-ithc-api-hmcts-net
        host_name_suffix: ithc.api.hmcts.net
        ssl_host_name_suffix: ithc.api.hmcts.net
